language: node_js

node_js:
  - "9" # 사용하고 싶은 node.js 버전을 지정합니다.

branches:
  only:
  - source # 소스 파일이 존재하는 브랜치입니다. 참고 문서에서는 source이지만 저는 local를 사용해왔습니다.

before_install:
- npm install -g hexo

install:
- npm install

before_script:
- git config --global user.name suitelab
- git config --global user.email yoonwoosik12@naver.com
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
- hexo clean
- hexo generate
- hexo deploy
# - git submodule init
# - git submodule update
# - npm run b # 저는 자체 테마를 gitsubmodule로 등록되어 있기에 테마 파일을 빌드 해주었습니다.
# - npm run p # hexo clean && hexo depoly -g
